# Generated by Django 5.0.3 on 2024-04-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_collection_featured_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
    ]
