# Generated by Django 5.0.3 on 2024-04-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_user_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'can cancel order')]},
        ),
    ]
