# Generated by Django 5.0.3 on 2024-04-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='lable',
            new_name='label',
        ),
    ]
